### ISSUE TITLE
MIME-Version Header twice in email

### ISSUE THREAD

**Issue by mediafinger** [mailgun/mailgun-ruby#194] opened 2020-04-20 15:55 UTC
Hey 😃 

we are using the mailgun-ruby gem in version 1.2.0 which already fixed the issue of some duplicated headers (In our case: "Reply-to").

https://github.com/mailgun/mailgun-ruby/releases/tag/v1.2.0

But the emails we send (with Rails 5.2.4.2 and devise 4.7.1) contain the `Mime-Version: 1.0` header twice.

---

This is an issue for us (and every other user of this Mailgun gem), as mailservers that use https://www.amavis.org/ or similar software might discard those 'invalid' emails.

**Comment by RemcodM** [comment] 2020-05-19 08:22
+1: We're experiencing this issue too. So far I have seen only one mailserver that drops e-mails because of this issue, but the fact that these mailservers exists is a problem for deliverability. When possible, I would like to see this fixed.

**Comment by shusugmt** [comment] 2020-06-05 13:56
I'm also facing the issue caused by this problem that the mail with DKIM-Signature: header signed by mailgun sent to Exchange (o365) will end up being marked as `dkim=fail` by Exchange since they seems to merge duplicated `Mime-Version:` header into one before it calculates the hash of the mail, which obviously breaks the hash.

```
# DKIM-Signature added by mailgun
# You can see that two Mime-Version: is used for bh
DKIM-Signature: a=rsa-sha256; v=1; c=relaxed/relaxed; d=example.com; q=dns/txt; s=k1; t=1591361834; h=Mime-Version: Content-Type: Subject: From: To: Mime-Version: Message-Id: Sender: Date: Content-Transfer-Encoding; bh=(snip); b=(snip)
```

I did a quick test and found out that passing extra `h:mime-version` param to [Message API endpoint](https://documentation.mailgun.com/en/latest/api-sending.html#sending) will cause duplicate `Mime-Version:` header appearing.

```
[47] pry(#<Railgun::Mailer>)> test_message
=> {
             :from => "no-reply@example.com",
               :to => "hoge@example.com",
          :subject => "test",
             :text => "You will receive a mail with two Mime-Version: in header!",
  "h:mime-version" => "1.0" # <- this part is problematic!!
}
[48] pry(#<Railgun::Mailer>)> @mg_client.send_message(@domain, test_message)
```

If I remove `h:mime-version` key from above hash and pass it to `Mailgun::Client#send_message`, the mail sent from mailgun will only have one `Mime-Version:`. So I guess we **should not** pass `h:mime-version` param at any time calling this API.

QUICK FIX: Monkey-patch to include `mime-version` in `IGNORED_HEADERS`
```
require 'mailgun-ruby'
Railgun::Mailer.send(:remove_const, :IGNORED_HEADERS) if Railgun::Mailer.constants.include?(:IGNORED_HEADERS)
Railgun::Mailer::IGNORED_HEADERS = %w[ to from subject reply-to mime-version ]
```

This will prevent `h:mime-version` key being added in `transform_for_mailgun`
https://github.com/mailgun/mailgun-ruby/blob/master/lib/railgun/mailer.rb#L76

There's a small caveat: debug log will be incorrect and a bit confusing:
```
[railgun] ignoring header (using envelope instead): mime-version
# Mime-Version is not a property of email envelope!
```

**Comment by darmenise** [comment] 2020-11-13 14:44
Same here, and this is causing the following **permanent delivery error** with a few of our clients. Please help us solve this because this issue is **damaging our business**!

```
The message WAS NOT relayed to:
  <acme@example.org>:
   554 5.6.0 Bounce, id=11252-07 - BAD HEADER

This nondelivery report was generated by the program amavisd-new at host
alice.acme.it. Our internal reference code for your message is
11252-07/BjEs4eWY2Xfz

INVALID HEADER

  Duplicate header field: "MIME-Version"
```

**Comment by Retttro** [comment] 2021-04-05 08:01
Version 1.2.4 with the fix is released. Closing.
https://github.com/mailgun/mailgun-ruby/releases/tag/v1.2.4

**Closed by Retttro** 2021-04-05 08:01 UTC
